apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: build-suite-test-component-image-url-tsts
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: build-suite-test-component-image-url-tsts
    app.kubernetes.io/part-of: test-app-iuwj
  name: build-suite-test-component-image-url-tsts
  namespace: build-e2e-specific-image-url-jjoa
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: build-suite-test-component-image-url-tsts
status:
  loadBalancer: {}
